### ISSUE TITLE
'$' is not defined in google-token.js

### ISSUE THREAD

**Issue by mohamed-ea** [Frozenfire92/EmberAuthTutorial#2]
it was a useful tutorial, thanks a lot
it worked like a charm with default google setting, but with google-token i get these 2 errors on the console :

```
torii-providers/google-token.js: line 47, col 16, '$' is not defined.
torii-providers/google-token.js: line 31, col 11, 'client_id' is defined but never used.
2 errors
```

and the pop-up appears and closes instantly without letting me to login

**Comment by ethanharstad** [comment]
I assume you are using ember-cli and the error is coming from js-hint. You can access `$` as `Ember.$` instead. As for the second error you can simply remove that line since `client_id` is unused.

**Comment by Frozenfire92** [comment]
That part of the tutorial I used jquery which is the $. Include it in your app and it will be resolved. Alternatively do a get request manually

**Comment by mohamed-ea** [comment]
thanks for your answers, i agree about the second error
Frozenfire92: it's already included jquery but still get same error

```
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    {{content-for 'head'}}
    <link rel="stylesheet" href="assets/vendor.css">
```

ethanharstad: being new to ember i can't figureout how to use your solution, I tried this : Ember.$.get(...) but got 'Ember' is not defined

**Comment by ethanharstad** [comment]
What you are experiencing is js-hint getting mad about you not importing the modules that you are using, you can google ES6 modules for more information. Your code should work as it stands if those are the only warnings you are seeing. Jquery ($) is already loaded by ember by the time you try to use it in your authenticator. It is good practice to explicitly import any module you use, which is why js-hint was warning you.
`import Ember from 'ember';`
at the top of your file will load the ember module, where you can access jquery by doing `Ember.$`. If you want a nicer name for it you can add
`var $ = Ember.$;`
after the import statement and then you can refer to jquery as just `$`.

**Comment by Frozenfire92** [comment]
Did that fix it for you @mohamed3ali ? is this still an issue?

**Comment by mohamed-ea** [comment]
yes it solved the problem, thanks a lot
